plink --bfile merged_QC-updated-chr1 --recode vcf --out merged_QC-updated-chr1-vcf
plink --bfile merged_QC-updated-chr2 --recode vcf --out merged_QC-updated-chr2-vcf
plink --bfile merged_QC-updated-chr3 --recode vcf --out merged_QC-updated-chr3-vcf
plink --bfile merged_QC-updated-chr4 --recode vcf --out merged_QC-updated-chr4-vcf
plink --bfile merged_QC-updated-chr5 --recode vcf --out merged_QC-updated-chr5-vcf
plink --bfile merged_QC-updated-chr6 --recode vcf --out merged_QC-updated-chr6-vcf
plink --bfile merged_QC-updated-chr7 --recode vcf --out merged_QC-updated-chr7-vcf
plink --bfile merged_QC-updated-chr8 --recode vcf --out merged_QC-updated-chr8-vcf
plink --bfile merged_QC-updated-chr9 --recode vcf --out merged_QC-updated-chr9-vcf
plink --bfile merged_QC-updated-chr10 --recode vcf --out merged_QC-updated-chr10-vcf
plink --bfile merged_QC-updated-chr11 --recode vcf --out merged_QC-updated-chr11-vcf
plink --bfile merged_QC-updated-chr12 --recode vcf --out merged_QC-updated-chr12-vcf
plink --bfile merged_QC-updated-chr13 --recode vcf --out merged_QC-updated-chr13-vcf
plink --bfile merged_QC-updated-chr14 --recode vcf --out merged_QC-updated-chr14-vcf
plink --bfile merged_QC-updated-chr15 --recode vcf --out merged_QC-updated-chr15-vcf
plink --bfile merged_QC-updated-chr16 --recode vcf --out merged_QC-updated-chr16-vcf
plink --bfile merged_QC-updated-chr17 --recode vcf --out merged_QC-updated-chr17-vcf
plink --bfile merged_QC-updated-chr18 --recode vcf --out merged_QC-updated-chr18-vcf
plink --bfile merged_QC-updated-chr19 --recode vcf --out merged_QC-updated-chr19-vcf
plink --bfile merged_QC-updated-chr20 --recode vcf --out merged_QC-updated-chr20-vcf
plink --bfile merged_QC-updated-chr21 --recode vcf --out merged_QC-updated-chr21-vcf
plink --bfile merged_QC-updated-chr22 --recode vcf --out merged_QC-updated-chr22-vcf
plink --bfile merged_QC-updated-chr23 --recode vcf --out merged_QC-updated-chr23-vcf